development:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: fedna
      password: password

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: neeraj
      password: neeraj@2019
cucumber:
  <<: *test
